### ISSUE TITLE
How to interpolate between faces? 

### ISSUE THREAD

**Issue by ligaozhe** [harryliew/WGAN-QC#1]
Hi, I am very interested in your work WGAN-QC, especially the interpolation between faces. I saw the result in your paper but not in the code. Could you please tell me how to do? I have asked same question via email. Thanks a lot!

**Comment by harryliew** [comment]
I think you can implement the interpolation code by yourself. It's quite easy. You randomly sample two noises from a Gaussian distribution and linearly interpolate between them. Then, you feed the two noises and the interpolated vectors into the trained generator to generate images. In this way, you get the interpolated images.
